# Generated by Django 6.0.7 on 2026-07-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('lease', 'billing_period', 'kind')},
        ),
    ]
