# Generated by Django 6.0.7 on 2026-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='lease_documents/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('default', 'Default')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
