# Generated by Django 6.0.7 on 2026-07-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_decouple_gas_billing_from_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_revisions', to='billing.lease')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
