# Generated by Django 6.0.7 on 2026-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivendaylog',
            name='kind',
            field=models.CharField(choices=[('driven', 'Driven'), ('day_off', 'Day off'), ('other_ride', 'Other ride')], default='driven', max_length=16),
        ),
    ]
