# Generated by Django 6.0.7 on 2026-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_drivendaylog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_amount_sats',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_txid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_watch_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16),
        ),
    ]
