# Generated by Django 6.0.7 on 2026-08-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_btc_address_invoice_btc_amount_sats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_credited_txid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_credited_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remainder_owed_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16),
        ),
    ]
