# Generated by Django 6.0.7 on 2026-08-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_btc_credited_txid_invoice_btc_credited_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoicelineitem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='btc_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
