# Generated by Django 6.0.7 on 2026-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_btc_line_item_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('partial', 'Partially Paid'), ('underpaid', 'Underpaid'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16),
        ),
    ]
