# Generated by Django 6.0.7 on 2026-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_backfill_btc_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_overpaid_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
