# Generated by Django 6.0.7 on 2026-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_invoice_stripe_round_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivendaylog',
            name='half_leg',
            field=models.CharField(blank=True, choices=[('drop_off', 'Drop-off'), ('pick_up', 'Pick-up')], default='', max_length=16),
        ),
    ]
