"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings.py lives at src/config/settings.py; BASE_DIR is the backend/
# project root (where .env and db.sqlite3 live), two levels up.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default: a shared fallback key would let anyone forge signed data
# (sessions, tokens) across every install that forgot to set this.
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so a deployment that forgets to set DEBUG doesn't
# leak stack traces/settings; local dev sets DEBUG=True via .env.
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"]
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",
    "billing",
    "payments",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:5173"]
)
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # Fail closed: every current view already sets its own
    # permission_classes explicitly, so this changes no existing
    # behavior. It exists so a future view that forgets to set
    # permission_classes is private by default instead of silently
    # public.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Scoped throttles for the anonymous (AllowAny) auth endpoints, to
    # stop unlimited magic-link email sends / token-guessing attempts.
    "DEFAULT_THROTTLE_RATES": {
        "magic_link_request": "5/hour",
        "magic_link_verify": "20/hour",
        "btc_claim_submit": "10/hour",
    },
    # How many trusted reverse proxies sit in front of the app. 0 (the
    # default) makes throttling key on REMOTE_ADDR and ignore
    # X-Forwarded-For entirely, which is correct with no proxy in
    # front (local dev). Behind CloudFront + Caddy in production this
    # must be 1, or the magic-link throttles above key on the proxy's
    # address instead of the real client's.
    "NUM_PROXIES": env.int("NUM_PROXIES", default=0),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "RentMeBro API",
    "DESCRIPTION": "Rent and utility billing API",
    "VERSION": "0.1.0",
}

# JWT chosen over session/cookie auth: frontend and backend are on
# separate origins, and a future mobile app can reuse bearer-token
# auth without cookie/SameSite/CSRF complications.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # A refresh is single-use: each one issues a new refresh token and
    # blacklists the one just spent, so a stolen refresh token can't be
    # replayed after the legitimate client next refreshes.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:5173")

# TLS terminates in front of the app (CloudFront/Caddy in production),
# so Django itself never sees a direct HTTPS connection. This tells it
# to trust the proxy-injected header instead of REMOTE_ADDR's scheme,
# which SECURE_SSL_REDIRECT and the "secure cookie" settings below all
# depend on to work correctly.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Off by default so local dev (plain HTTP) isn't redirect-looped;
# production sets these via env.
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Path prefix for the Django admin, overridable so the real path isn't
# published in a public repo. Defense-in-depth only: the primary
# control is restricting administrative surfaces at the edge/proxy in
# production, not this path being unguessable.
ADMIN_URL = env("ADMIN_URL", default="admin/")

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="config.email_backends.PlainTextConsoleEmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
# .example is an IANA-reserved documentation TLD (RFC 2606): it is
# syntactically valid but never delivers mail, unlike the previous
# .local default, which is a real reserved TLD that some resolvers
# treat as routable and others reject outright. A real deployment
# always sets this via env.
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL", default="noreply@rentmebro.example"
)

STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_CONNECT_WEBHOOK_SECRET = env(
    "STRIPE_CONNECT_WEBHOOK_SECRET", default=""
)

MEMPOOL_API_BASE_URL = env(
    "MEMPOOL_API_BASE_URL", default="https://mempool.space/api"
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL", default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    )
}
# Reuse connections across requests instead of opening one per request.
# 0 (Django's default) is correct for SQLite (no connection to reuse);
# production Postgres sets this via env.
DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=0)


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads, e.g. lease documents via Lease.document).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Media storage: S3 when a bucket is configured (production), local
# filesystem otherwise (local dev, matching prior behavior). The
# instance filesystem is not a durable home for lease PDFs in
# production, so this is mandatory before deploy, not an optimization.
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")

STORAGES = {
    "default": (
        {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "querystring_auth": True,
            },
        }
        if AWS_STORAGE_BUCKET_NAME
        else {"BACKEND": "django.core.files.storage.FileSystemStorage"}
    ),
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}
