# Generated by Django 6.0.7 on 2026-07-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_unique_email_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
