# Generated by Django 6.0.7 on 2026-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_stripe_account_id_user_stripe_charges_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='btc_payments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='btc_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
