# Generated by Django 6.0.7 on 2026-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_magiclinktoken_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
